### PR TITLE
[Feature] add browser build support

### PR DESCRIPTION
**Pull request by saikat-mitra**
Fixes https://github.com/rdkcentral/Lightning-CLI/issues/128

### CODE REVIEW

**Comment by saikat-mitra** [comment]
Hi @wouterlucas 
can you please help review this PR?

**Comment by saikat-mitra** [comment]
@michielvandergeest Can you please help with the review?

**Comment by michielvandergeest** [comment]
@saikat-mitra we are in the process of testing the changes in this PR

**Comment by saikat-mitra** [comment]
awesome! thanks @michielvandergeest!

**Comment by saikat-mitra** [comment]
@michielvandergeest  any update on this?

**Comment by sandeep-vedam** [comment]
Hey @saikat-mitra , Thanks for your contribution.

We have added these changes with the PR #193 .

**Pull request closed without merging**
