### PR TITLE
Typescript for rollup

### PR DESCRIPTION
**Pull request by JanSunavec**
**Typescript support**

For rollup only.

### CODE REVIEW

**Comment by JanSunavec** [comment]
Any reviews, comments?

**Comment by michaelgosling** [comment]
Is there any timeline for this? I'm hoping to adopt Typescript with a lightning project asap before the development gets too far and converting becomes too complex.

**Comment by JanSunavec** [comment]
@michielvandergeest Who is responsible to make PR review?

**Comment by JanSunavec** [comment]
PR is not in progress. Let's review or close it.

**Comment by Angel-Cortez** [comment]
@JanSunavec, you have babel imported twice: https://github.com/rdkcentral/Lightning-CLI/blob/3b268652396a8b197bac2bb401e26604ea0bf7e3/src/configs/rollup.es6.config.js#L35

**Comment by JanSunavec** [comment]
> @JanSunavec, you have babel imported twice:
> 
> https://github.com/rdkcentral/Lightning-CLI/blob/3b268652396a8b197bac2bb401e26604ea0bf7e3/src/configs/rollup.es6.config.js#L35

Thanks. Fixed

**Comment by michielvandergeest** [comment]
@JanSunavec thanks for your PR. We have made a release of the Lightning-CLI last week (v2.8.0) which contains basic Typescript support. Closing this PR in favor of v2.8.0.

**Pull request closed without merging**
