### PR TITLE
App variables from process.env are now available

### PR DESCRIPTION
**Pull request by Drulokia**
In the app you alse have the APP_ variables from process.env now https://github.com/rdkcentral/Lightning-CLI/issues/214

### CODE REVIEW

**Comment by michielvandergeest** [comment]
@Drulokia I don't really see how this PR fixes the described issue #214 . In my tests with this version of the CLI, the APP variables passed in via `provess.env` are not available in the Application. Moreover the APP variables specified in the .env file are _also_ not available (which I guess makes sense, since the code related to `dotenv` has been removed in the PR).

Or am I missing something?

**Comment by ricardo-a-alves-alb** [comment]
I believe that what was needed to be done was merge `dotenv` variables with `process.env` variables. This way, only the environment variables that were set before running the CLI command or the operating system environment variables will be available on `process.env`.

**Comment by Drulokia** [comment]
https://github.com/Drulokia/Lightning-CLI/blob/eb5d45697f339990296d48801fecd107103faf03/bin/index.js#L23
As defined in the documentation of dotenv this line will already merge the .env file in the process.env

I checked again and so far i can see the APP_ variables are available in the App.
Make sure you use the full variable `process.env.APP_myvar` as process.env will not give you a object. (This was also the case before i changed the code).

checked if the environment variables are merged with process.env -> they are
checked if they both exist with different values they change -> they do
the variables are accessible in the app when they start with APP_ and you have to use to full name (process.env.APP_TOKEN for example)

**Review by uguraslan — APPROVED** [review]
LGTM

**Review by michielvandergeest — APPROVED** [review]

**Comment by uguraslan** [comment]
I tested the change:

* `process.env` variables and `.env` variables are merged: ✅ 
* `process.env` variables take precedence over `.env` variables on naming collisions: ✅ 
* All defined app variables (ones starting with `APP_`) are available to app code with the default bundler: ✅

**Pull request merged**
