### PR TITLE
Bump esbuild 0.12.20

### PR DESCRIPTION
**Pull request by JanSunavec**
Esbuild is still not ready for production. Ver 0.8.x has many issues but version 0.12.20 is very promising.

### CODE REVIEW

**Comment by JanSunavec** [comment]
@michielvandergeest Version 0.8.x is really old. Let's bump it..

**Comment by michielvandergeest** [comment]
I think this should be fine ... double checking with @erikhaandrikman: anything against bumping to this version of ESbuild?

@JanSunavec just fo you to be aware, that atm we're still considering the use esbuild as lightning App bundler experimental

**Comment by JanSunavec** [comment]
@michielvandergeest I know that esbuild is still not production ready. On the other hand we are able create better production build with 0.12.20 against rollup.

**Comment by JanSunavec** [comment]
Any progress guys?

**Review by michielvandergeest — APPROVED** [review]

**Pull request merged**
