### PR TITLE
Updated the licenses and notice

### PR DESCRIPTION
**Pull request by sandeep-vedam**
Updated the licenses and notices for licence compliance

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Sandeep: Not sure what's happening here.  The changes I requested in PR237 are still needed.  The compliance checking will complain until I clear it off manually (as happened with the first commit here).  Also, please use a generic YEAR and COPYRIGHT HOLDER in the MIT license so it can apply to all MIT licensed copyright owners in the NOTICE file.
- Martin Hughes, RDK CMF Compliance Team

**Review by uguraslan — APPROVED** [review]
LGTM

**Comment by uguraslan** [comment]
Hi @mhughesacn, with #237, a few lines of code did not pass the Blackduck scan. But with this PR, we are removing those lines of code and adding our own version of it. As the code that requires attribution is being removed, I think we don't need to change the license or the notice files any more. But we will be waiting for your comment to get a confirmation before merging this PR.

**Comment by mhughesacn** [comment]
Thanks @uguraslan : I confirmed this with Michiel van der Geest on slack last week.  You are good to go. - Martin

**Pull request merged**
