### PR TITLE
BD-901:Relicense Lightning-CLI to Metrological 

### PR DESCRIPTION
**Pull request by mallikarjuna54**
Reason for change:Relicense Lightning-CLI to Metrological Apache update 
Test Procedure: Jenkin build should pass after License header changes for RDK for listed repos
BD-901:Relicense Lightning-CLI to Metrological Apache update 
Risks: None

### CODE REVIEW

**Review by mhughesacn — CHANGES_REQUESTED** [review]
Hi Mallikarjuna, You need to rebase the PR and check if there are any more RDK headers.
I found the following, either with no header or RDK header:
	fixtures/lightning-app/src/App.js
	src/actions/dist.js
	src/configs/esbuild.es5.config.js
	src/configs/esbuild.es6.config.js
	src/helpers/dist.js
	src/helpers/localinstallationcheck.js
	src/plugins/esbuild-alias.js

Please will you add a metrological header, either new or in place of the RDK one.
Thank you.

**Comment by mhughesacn** [comment]
I approve of these changes and have cleared the complaints in the tool.  Over to Metrological to merge please.

**Comment by pradeeptakdas** [comment]
Hi @woutermeek 
Please merge this PR if you are Happy. Thanks!

**Comment by michielvandergeest** [comment]
Closing in favor of PR #133

**Pull request closed without merging**
