### PR TITLE
Encode imported images with base64

### PR DESCRIPTION
**Pull request by lewispeel**
## Feature
Use images using the `import` statement.

### Problem
We're developing a shared UI component library and each component could potentially have its own images. Currently the Lightning CLI insists all images are stored in the `static` directory of the application in order for them to bundled up using rollup. Images inside the component library won't be bundled as the CLI doesn't know they exist.

### Solution
Use [@rollup/plugin-image](https://github.com/rollup/plugins/tree/master/packages/image) to find all imported images and encode them using base64. This means they will be 33% larger than the size on disk. You should therefore only use this for small images where the convenience of having them available on startup (e.g. rendering immediately without co-ordinating asynchronous loading of several images) outweighs the cost.

### Usage
```
import { Lightning } from '@lightningjs/sdk'

import logo from './logo.png'

export default class App extends Lightning.Component {
  static _template() {
    return {
      Logo: {
        src: logo,
      },
    }
  }
}
```

### CODE REVIEW

**Comment by lewispeel** [comment]
Hi @michielvandergeest - is there anything else I need to do to get this merged?

**Comment by michielvandergeest** [comment]
Hi @lewispeel, sorry for the delay in getting back to this. The plan was actually to review this PR for last weeks release, but some other stuff took priority. I expect we can include it in the next one, though (hopefully end of this week)!

I think the PR looks good, there's just one issue with the `destDir` being hardcoded to `build/static`, whereas that can be configured that via _Environment variables_ (https://rdkcentral.github.io/Lightning-CLI/#/environmentvariables?id=lng_build_folder).

If we can fix that we should be good to go, I guess.

**Comment by lewispeel** [comment]
Thanks @michielvandergeest - good point! I've updated the configs to make use of the environment variable, which defaults to `build` if nothing is found.

**Comment by lewispeel** [comment]
@michielvandergeest I've swapped out [@rollup/plugin-url](https://github.com/rollup/plugins/tree/master/packages/url) for [@rollup/plugin-image](https://github.com/rollup/plugins/tree/master/packages/image) as the former only worked with images imported from the main application. The latter works with any image, including from external dependencies. I'll update the original PR.

**Review by michielvandergeest — APPROVED** [review]
LGTM. Thanks for the contribution 👍 
This should end up in the next CLI-release

**Pull request merged**
